const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './features/**/*.{ts,tsx}',
    '../../packages/ui/src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#800020', // Deep Cathedral Burgundy
          50: '#FDF2F4',
          100: '#FCE7EB',
          200: '#F7C5CD',
          300: '#EE96A5',
          400: '#DE5D76',
          500: '#C72C4F',
          600: '#A31336',
          700: '#800020',
          800: '#64041C',
          900: '#420615',
          950: '#26020A',
          foreground: '#FFFFFF',
        },
        secondary: {
          DEFAULT: '#003366', // Marian Royal Blue
          50: '#F0F5FA',
          100: '#DDE9F4',
          200: '#B2D0E8',
          300: '#7CB1D8',
          400: '#488EC4',
          500: '#256FA9',
          600: '#14548A',
          700: '#0C406E',
          800: '#003366',
          900: '#00254D',
          950: '#001833',
          foreground: '#FFFFFF',
        },
        gold: {
          DEFAULT: '#D4AF37', // Liturgical Sacred Gold
          50: '#FBF8EE',
          100: '#F6EED5',
          200: '#ECDCAB',
          300: '#DFC77B',
          400: '#D4AF37',
          500: '#B89224',
          600: '#947219',
          700: '#705415',
          800: '#4E3A13',
          900: '#2A1F0B',
          foreground: '#181F2C',
        },
        burgundy: {
          DEFAULT: '#800020',
          50: '#FDF2F4',
          100: '#FCE7EB',
          200: '#F7C5CD',
          300: '#EE96A5',
          400: '#DE5D76',
          500: '#C72C4F',
          600: '#A31336',
          700: '#800020',
          800: '#64041C',
          900: '#420615',
          950: '#26020A',
        },
        marian: {
          DEFAULT: '#003366',
          50: '#F0F5FA',
          100: '#DDE9F4',
          200: '#B2D0E8',
          300: '#7CB1D8',
          400: '#488EC4',
          500: '#256FA9',
          600: '#14548A',
          700: '#0C406E',
          800: '#003366',
          900: '#00254D',
          950: '#001833',
        },
        ivory: {
          DEFAULT: '#FAF8F5',
          50: '#FDFAF7',
          100: '#FAF8F5',
          200: '#F3EFE8',
          300: '#E8E1D5',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', ...defaultTheme.fontFamily.sans],
        serif: ['var(--font-playfair)', 'Playfair Display', ...defaultTheme.fontFamily.serif],
        cinzel: ['var(--font-cinzel)', 'Cinzel', ...defaultTheme.fontFamily.serif],
        heading: ['var(--font-playfair)', 'Playfair Display', 'Georgia', ...defaultTheme.fontFamily.serif],
        display: ['var(--font-playfair)', 'Playfair Display', 'Georgia', ...defaultTheme.fontFamily.serif],
        tamil: ['Noto Sans Tamil', 'Noto Serif Tamil', 'sans-serif'],
        'tamil-serif': ['Noto Serif Tamil', 'serif'],
      },
      borderRadius: {
        lg: '0.5rem',
        md: 'calc(0.5rem - 2px)',
        sm: 'calc(0.5rem - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          from: { opacity: '0', transform: 'translateY(-20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-left': {
          from: { opacity: '0', transform: 'translateX(-32px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(32px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.92)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'zoom-slow': {
          from: { transform: 'scale(1)' },
          to: { transform: 'scale(1.08)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-in-up': 'fade-in-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-in-down': 'fade-in-down 0.8s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in-left': 'slide-in-left 0.8s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in-right': 'slide-in-right 0.8s cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in': 'scale-in 0.7s cubic-bezier(0.16, 1, 0.3, 1) both',
        'zoom-slow': 'zoom-slow 22s ease-out forwards',
        shimmer: 'shimmer 2s infinite linear',
      },
    },
  },
  plugins: [],
};
