-- AlterEnum
ALTER TYPE "FamilyRelationship" ADD VALUE IF NOT EXISTS 'BROTHER';
ALTER TYPE "FamilyRelationship" ADD VALUE IF NOT EXISTS 'SISTER';
ALTER TYPE "FamilyRelationship" ADD VALUE IF NOT EXISTS 'GRANDSON';
ALTER TYPE "FamilyRelationship" ADD VALUE IF NOT EXISTS 'GRANDDAUGHTER';
ALTER TYPE "FamilyRelationship" ADD VALUE IF NOT EXISTS 'RELATIVE';

-- AlterTable
ALTER TABLE "family_members" ADD COLUMN IF NOT EXISTS "tamilName" TEXT,
ADD COLUMN IF NOT EXISTS "preferredName" TEXT,
ADD COLUMN IF NOT EXISTS "placeOfBirth" TEXT,
ADD COLUMN IF NOT EXISTS "nationality" TEXT,
ADD COLUMN IF NOT EXISTS "alternatePhone" TEXT,
ADD COLUMN IF NOT EXISTS "address" TEXT,
ADD COLUMN IF NOT EXISTS "city" TEXT,
ADD COLUMN IF NOT EXISTS "pincode" TEXT,
ADD COLUMN IF NOT EXISTS "isFamilyHead" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "isLivingWithFamily" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "parentGuardian" TEXT,
ADD COLUMN IF NOT EXISTS "schoolInstitution" TEXT,
ADD COLUMN IF NOT EXISTS "educationLevel" TEXT,
ADD COLUMN IF NOT EXISTS "courseDegree" TEXT,
ADD COLUMN IF NOT EXISTS "yearOfStudy" TEXT,
ADD COLUMN IF NOT EXISTS "employer" TEXT,
ADD COLUMN IF NOT EXISTS "designation" TEXT,
ADD COLUMN IF NOT EXISTS "baptismParish" TEXT,
ADD COLUMN IF NOT EXISTS "baptismPlace" TEXT,
ADD COLUMN IF NOT EXISTS "baptismRegisterNo" TEXT,
ADD COLUMN IF NOT EXISTS "hasBaptismCertificate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "receivedFirstCommunion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "firstHolyCommunionParish" TEXT,
ADD COLUMN IF NOT EXISTS "firstHolyCommunionRegisterNo" TEXT,
ADD COLUMN IF NOT EXISTS "confirmationParish" TEXT,
ADD COLUMN IF NOT EXISTS "confirmationRegisterNo" TEXT,
ADD COLUMN IF NOT EXISTS "spouseName" TEXT,
ADD COLUMN IF NOT EXISTS "marriageParish" TEXT,
ADD COLUMN IF NOT EXISTS "marriageRegisterNo" TEXT,
ADD COLUMN IF NOT EXISTS "hasMarriageCertificate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "anbiyamRole" TEXT,
ADD COLUMN IF NOT EXISTS "ministryInvolvement" TEXT,
ADD COLUMN IF NOT EXISTS "choirInvolvement" TEXT,
ADD COLUMN IF NOT EXISTS "isAltarServer" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "catechismInvolvement" TEXT,
ADD COLUMN IF NOT EXISTS "isYouthMinistry" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "otherParishService" TEXT,
ADD COLUMN IF NOT EXISTS "documents" JSONB;
